### ISSUE TITLE
Implement value encoding and decoding

### ISSUE THREAD

**Issue by virgil-serbanuta** [Pi-Squared-Inc/rust-demo-semantics#142]
Depends on #135 

We would need to add the following the Helpers trait: `fn encodeU8(Bytes, u8) -> Bytes`, `fn encodeU16(Bytes, u16) -> Bytes` ... to the Bytes type (these would append to the bytes object).

We would need to also add `fn decodeU8(Bytes) -> (Bytes, u8, bool)`, ... - these would return the decoded value and the remaining Bytes, and a success flag.

**Comment by ACassimiro** [comment]
Addressed in #167 and #171.
